#define BUTTON_LEFT_PIN PC4
#define BUTTON_LEFT_PORT PORTC
#define BUTTON_LEFT_GROUP PINC
#define BUTTON_LEFT_DDR DDRC

#define BUTTON_RIGHT_PIN PC5
#define BUTTON_RIGHT_PORT PORTC
#define BUTTON_RIGHT_GROUP PINC
#define BUTTON_RIGHT_DDR DDRC

#define LONG_PRESS_THRESHOLD 1000  // 1 second